name: Bug report
description: Report a reproducible bug in primer-scout
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide enough detail for us to reproduce quickly.

  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: What behavior did you observe, and what did you expect?
      placeholder: Short, concrete summary
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Include exact commands, input files, and flags.
      placeholder: |
        1. Run: primer-scout ...
        2. Input file ...
        3. Observed output ...
    validations:
      required: true

  - type: textarea
    id: data
    attributes:
      label: Minimal input sample
      description: Provide tiny FASTA/primer examples that reproduce the issue.
      render: text
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: primer-scout version
      placeholder: e.g. v0.1.0
    validations:
      required: true

  - type: input
    id: rust
    attributes:
      label: Rust version
      placeholder: rustc --version output

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. macOS 15 / Ubuntu 24.04
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or error output
      render: shell
